CREATE DATABASE [Corp2Con]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Corp2Con', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Corp2Con.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Corp2Con_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Corp2Con_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Corp2Con] SET COMPATIBILITY_LEVEL = 120
GO
ALTER DATABASE [Corp2Con] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Corp2Con] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Corp2Con] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Corp2Con] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Corp2Con] SET ARITHABORT OFF 
GO
ALTER DATABASE [Corp2Con] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Corp2Con] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Corp2Con] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [Corp2Con] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Corp2Con] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Corp2Con] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Corp2Con] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Corp2Con] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Corp2Con] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Corp2Con] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Corp2Con] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Corp2Con] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Corp2Con] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Corp2Con] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Corp2Con] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Corp2Con] SET  READ_WRITE 
GO
ALTER DATABASE [Corp2Con] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Corp2Con] SET  MULTI_USER 
GO
ALTER DATABASE [Corp2Con] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Corp2Con] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [Corp2Con] SET DELAYED_DURABILITY = DISABLED 
GO
USE [Corp2Con]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [Corp2Con] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

USE [Corp2Con]
GO
CREATE USER [corp2conuser] FOR LOGIN [corp2conuser]
GO
USE [Corp2Con]
GO
ALTER USER [corp2conuser] WITH DEFAULT_SCHEMA=[dbo]
GO
USE [Corp2Con]
GO
ALTER ROLE [db_owner] ADD MEMBER [corp2conuser]
GO
use master