// <auto-generated />
namespace Talent21.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CandidatesareContractors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CandidatesareContractors));
        
        string IMigrationMetadata.Id
        {
            get { return "201507180949071_Candidates are Contractors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
