// <auto-generated />
namespace Talent21.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class JobsandContractorshaveskills : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JobsandContractorshaveskills));
        
        string IMigrationMetadata.Id
        {
            get { return "201507010640532_Jobs and Contractors have skills"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
